### ISSUE TITLE
Unit test a Controller: add a test for "controller as" use case

### ISSUE THREAD

**Issue by yanivefraim** [daniellmb/angular-test-patterns#7]
As "controller as" becomes more and more popular, I think this should be a mandatory pattern (I am willing to add a PR for it)

**Comment by daniellmb** [comment]
I'd love to see another contributor to this project. I always intended that this would be a community effort.

**Comment by yanivefraim** [comment]
Awesome. I'll try to free-up some time and join the effort... Seems like a great idea!

**Comment by daniellmb** [comment]
Yeah, that's my dilemma lots of great ideas and no time :)

**Comment by yanivefraim** [comment]
I started working on the `controller as` implementation. How do you thing it will be best to ad this: As a new pattern under `patterns/controller.md`? as a new file, something like `patterns/controlelrAs.ms`?
I tried adding it as a new pattern under `controller.md`, but I keep getting a strange error:
`Found 32 but expected 36 blocks`. Not sure what is this - any idea?

**Comment by daniellmb** [comment]
Yeah, I think a new file controllerAs.md would be best since the controller is going to have things on `this` instead of `scope` the unit tests won't look the same. As for the block count issue, unfortunatly the formatting of the md file has to follow a convention so it can [parse it into sections](https://github.com/daniellmb/angular-test-patterns/blob/master/spec/lib/parse.util.coffee.md#parse-markup-into-sections). That check is there to let you know it wasn't able to parse the file.

**Comment by daniellmb** [comment]
merged! :)
